development: 
  encoding: unicode
  adapter: postgresql
  username: pointsuser
  port: 5432
  host: localhost 
  database: points-dev
  password: points123

test: 
  encoding: unicode
  adapter: postgresql
  username: pointsuser
  port: 5432
  host: localhost
  database: points-test
  password: points123

production: 
  encoding: unicode
  adapter: postgresql
  username: pointsuser
  port: 5432
  host: localhost
  database: points-prod
  password: points123
